version: "3.5"
services:
  restapi:
    image: ghcr.io/arquisoft/lomap_en1a/restapi:latest
    ports:
      - "5080:5080"
      - "5443:5443"
  webapp:
    image: ghcr.io/arquisoft/lomap_en1a/webapp:latest
    ports:
      - "3080:3080"
      - "3443:3443"
    depends_on:
      - restapi
