version: "3.5"
services:
  restapi:
    image: ghcr.io/arquisoft/lomap_en1a/restapi:latest
    ports:
      - "5000:5000"
  webapp:
    image: ghcr.io/arquisoft/lomap_en1a/webapp:latest
    ports:
      - "443:443"
    depends_on:
      - restapi
deploy:
  name: Deploy over SSH
  runs-on: ubuntu-latest
  needs: [docker-push-restapi, docker-push-webapp]
  steps:
    - name: Deploy over SSH
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        mongo: ${{ secrets.MONGO_DATABASE_CONNECTION }}
        command: |
          wget https://raw.githubusercontent.com/arquisoft/lomap_en1a/master/docker-compose-deploy.yml -O docker-compose.yml
          docker-compose stop
          docker-compose rm -f
          docker-compose pull
          docker-compose up -d
