version: "3.5"
services:
  restapi:
    image: ghcr.io/arquisoft/lomap_en1a/restapi:latest
    ports:
      - "5000:5000"
  webapp:
    image: ghcr.io/arquisoft/lomap_en1a/webapp:latest
    ports:
      - "443:443"
    depends_on:
      - restapi
