@startuml
' Building Block View Diagram v1.0
' Level 1
skinparam actorStyle awesome
'-----------------------
'Definition of actors
'-----------------------
card LoMap {
    component Webapp as Frontend
    component RestAPI as Backend
    database Database
}


card "User" as UserDat {
    actor User
    database POD
}

rectangle "External Services" {
    cloud "Map Provider" as MapService
}

'-----------------------
'Definition of relations
'-----------------------
User -r-> Frontend : interacts
' Hidden relations help with spacing
User -[hidden]--- Frontend
User -d-> POD : manages
Frontend --> Backend
POD -l- Backend
Backend -d-> Database
Backend -r-> MapService


@enduml