@startuml
' Business Context Diagram v1.0
skinparam actorStyle awesome
'-----------------------
'Definition of actors
'-----------------------
actor User
database POD
database Database
hexagon LoMap
cloud "Map Provider" as MapService

'-----------------------
'Definition of relations
'-----------------------
User -r..> LoMap : Uses the services
User -d-> POD : Controlls permissions
POD <-> LoMap : Fetches data about the user
LoMap <-d-> Database : Stores link data
LoMap <- MapService : Provides the map

@enduml