[[section-system-scope-and-context]]
== System Scope and Context
In this chapter we will give a brief description of what will the scope of the project be, as well as for which context it is being created for.

The project is aimed at creating a software system for decentralized maps, where users can store their shared information in SOLID Pods. The application will be able to retrieve that data (given the permission from the user), and use it to display whatever markers the user might want to add.

(Insert diagram here)

== Business Context
The system is related with several parters, shown in the following diagram:

image::businessDiagram.svg[Business Diagram]

The elements shown in the diagram are explained here:

[options="header,footer"]
|=======================
|Partner          |Input             |Output
|User             |Application services |User data
|POD              |User data/request |User data
|LoMap            |User input        |Service to user
|(DataBase)       |User data request |User data
|(Deployment)     |Application data  |Application deployment
|(Image service)  |Image request     |Images
|(Map service)    |Map data request  |Map data 
|=======================

=== Technical Context

[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation with I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****

**<Diagram or Table>**

**<optionally: Explanation of technical interfaces>**

**<Mapping Input/Output to Channels>**
