[[section-solution-strategy]]
== Solution Strategy

Our language of choice is TypeScript, due to to the need of it for the next decisions involving libraries, which were taken. Also, the majority of the team was familiar with JavaScript,
which has similarities with TypeScript.

Regarding libraries, we are going to use React, for the front-end of the application, and Node.js for the back end, due to that we were recommended in the lectures to use React, and after 
investigating a bit, we found that Node.js works surprisingly well with React.

When it comes to storing information, we decided that we will use json files, because we were quite familiar with it and we think it will represent the information better than the other proposed
ones such as XML. And having a look to persiting the information, we will use a relational database, and PODS to store sensitive user data. When discussing about the possible databases,
 we found that the model we were trying to represent was easily mapped with a relationa approach, and from there, MariaDB and MySQL were proposed. From which we picked the second option
 since most of us were quite familiar with it.

Taking a quick peek at the general structure of the application, the usage of some patterns was debated, those being:
    -Command pattern: When accessing the database in CRUD operations.
    -Façade pattern: When dividing responsabilities among the layers.
    -MVC pattern: When assigning roles to the parts of the applications.
But these patterns were just taken into consideration since the application design phase has still not started.

