[[section-building-block-view]]


== Building Block View

=== Level 1: Whitebox Overall System

This is a high-level static overview of the system and all its building blocks. It shows the application components, the user-related components and the external services that the application uses.

The main actor for the application is the user, which interacts with the application and provides access to a POD on which its data is stored. The application is divided into the frontend –managing the user interaction–, and backend which interacts with external services.

This diagram is divided based on data ownership. Three main groups are considered:

- User: groups all user-related blocks.
- LoMap: groups all application-specific blocks.
- External Services: groups all other blocks that are not directly related to the user nor to the application.

image::BuildingBlockView-Level1.svg[Building Block View (Level 1)]

==== Contained BlackBoxes
[options="header"]
|===========================================================================================================
| Name            | Description                                                                                      
| User            | External user that provides its data through a POD and that makes use of the application services
| POD             | Privately holds all user data. The application asks for permission to access this information    
| Webapp          | Provides an user-friendly interface to access all application services                           
| LoMapCore       | Provides the services that the application offers. Connects to data sources to provide those services
| Database        | Holds all common data that the application needs to run
| Map Provider    | External service that provides map data to the application
| Image Provider  | External service that provides image data to the application
|===========================================================================================================

DISCLAIMER::
The following sections have been intentionally left partially completed. This is because the application is yet to be builded, so a lower level of abstraction is, as of now, speculation. Nevertheless, the general structure of the section is presented for guidance.

=== Level 2: Webapp
The Webapp encompasses all UI-related components of the application. ...

(insert diagram)

==== Contained BlackBoxes
[options="header"]
|===
| Name            | Responsibility
| Comp1   | Component 1 of the Webapp
| Comp2   | Component 2 of the Webapp
| Comp3   | Component 3 of the Webapp
| ... | ...
|===

==== Level 2: LoMapCore
The LoMapCore block encompasses all business-logic components, as well as data-source management and interaction with other services. ...

(insert diagram)

==== Contained BlackBoxes
[options="header"]
|===
| Name            | Responsibility
| RestAPI   | API that allows all the other parts of the application to connect to the LoMapCore
| Comp2   | Component 2 of the RestAPI
| Comp3   | Component 3 of the RestAPI
| ... | ...
|===

==== Database
The Database holds all common information that the application needs to run, such as cached data, ???, ...

TODO: Is it necessary to include a diagram for the Database?

==== MapService
The MapService is an external service, provided through an API, that allows LoMap to obtain the most recent and updated maps available, in order to avoid providing outdated information to the end user.

(insert API overview)

==== ImageService
The ImageService is an external service, planned to provide access to marker images. Its usage is, as of now, uncertain, as there is not yet clear whether this service will be needed. 

(insert API overview)
