[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== Login scenario

The user must be logged in to see and modify their personal data.

[plantuml,"Login scenario",png]
----
@startuml
actor User as "Alice"
participant Frontend
participant Backend
database Pod as "User's Pod"
Alice-> Frontend: Send credentials
Frontend-> Backend: Authentication Request
Backend-> Pod: Match credentials
Pod --> Backend: Return comparison results
Backend--> Frontend: Authentication response
Frontend-> Frontend: Response-based redirection
Frontend--> User: Result presentation
@enduml
----
=== Add location scenarios
[plantuml,"Add location scenario",png]
----
@startuml
actor User as "Alice"
participant Frontend
participant Backend
database DB as "General Purpose DB"
User-> Frontend: Send location data
Frontend-> Backend: Location data addition request
Backend-> DB: Insert location data
DB-> DB: Data insertion
DB--> Backend: Insertion results
Backend--> Frontend: Send feedback
Frontend-> Frontend: Feedback-based redirection
Frontend--> User: Feedback presentation
@enduml
----

=== Review location scenario
[plantuml,"Review location scenario",png]
----
@startuml
actor Alice
@enduml
----
