[[section-runtime-view]]
== Runtime View
The runtime view offers a different perspective of the structure of the application, revealing the process each request makes throughout the whole scope of the system.

=== Login scenario

This scenario describes a high-level overview of the process a user takes to log into the application, from the .

[plantuml,"Login scenario",svg]
----
@startuml
actor User as "Alice"
participant Frontend
participant Backend
participant IDP
database Pod as "User's Pod"

User -> Frontend: Login Request
Frontend -> Backend: Login Request
Backend -> IDP: Authentication Redirect
IDP --> User: Login form
IDP <-- User
IDP <-> Pod: Match credentials
IDP -> Backend: Redirect return with token
Backend -> Frontend: Authentication response
Frontend -> User: Result presentation
@enduml
----
=== Add location scenarios
This scenario describes the steps taken for a user to save a location to the system. This assumes the user is already logged in.

[plantuml,"Add location scenario",svg]
----
@startuml
actor User as "Alice"
participant Frontend
participant Backend
database DB as "General Purpose DB"
database POD

User-> Frontend: Send location data
Frontend-> Backend: Location data addition request
Backend-> DB: Insert location metadata
Backend-> POD: Insert location metadata

DB --> Backend: Insertion results
POD --> Backend: Insertion results
Backend--> Frontend: Send feedback
Frontend--> User: Feedback presentation
@enduml
----

=== View location details scenario
This scenario describes the process taken when a user requests to see the information of a given location. Like the last scenario, this one assumes the user is already logged in.

In this case, several PODs are accessed, as the comments, reviews and scores are stored in each poster's POD.

[plantuml,"View location details scenario",svg]
----
@startuml
actor User as "Alice"
participant Frontend
participant Backend
database DB as "General Purpose DB"
database PODs

User-> Frontend: Fetch location request
Frontend-> Backend: Send location identifier
Backend-> DB: Link data request
DB-> DB: Get link data
DB--> Backend: Process results
Backend -> Backend: Prepare requests
Backend -> PODs: Request data
Backend -> PODs
Backend -> PODs

PODs --> Backend: Return data
PODs --> Backend
PODs --> Backend

Backend--> Frontend: Location data

Frontend--> User: Result presentation

@enduml
----

=== Review location scenario
This scenario describes the process taken when a user wants to leave a review. This scenario follows from the last one.

[plantuml,"Review location scenario",svg]
----
@startuml
actor User as "Alice"
participant Frontend
participant Backend
database DB as "General Purpose DB"
database PODs

User -> Frontend: Review
Frontend -> Backend: Review contents
Backend -> DB: Review link data insertion
Backend -> PODs: Review data insertion

DB --> Backend: Insertion results
PODs --> Backend: Insertion results

Backend --> Frontend: Send feedback
Frontend --> User: Feedback presentation
@enduml
----
