[[section-deployment-view]]

== Deployment View
The deployment of the application is done, ideally, in an Azure Machine in the Microsoft Cloud. Inside, two Docker containers are deployed: one holds the RestAPI and the other holds the WebApp.

Also, the POD and the Database are cloud-based, so they are held in their respective provider's infrastructure.

[plantuml,"Deployment view",svg]
----
@startuml
skinparam actorStyle awesome

node UserM as "User Machine"{
    actor User
}

node Azure as "Azure Machine"{

    frame C2 as "Container 2"{
        component RestAPI
    }

    frame C1 as "Container 1"{
        component WebApp
    }
}

cloud Internet {
    node DBProv as "Database Provider"{
        database Database
    }
    node IDP as "Identity Provider"{
        database POD
    }

    node MapProv as "Map Provider"
}

'--------------

POD <-r- RestAPI
RestAPI -l-> Database
WebApp -r-> MapProv
DBProv -[hidden]- IDP
IDP -[hidden]- MapProv

Azure -[hidden]- UserM
WebApp -l- UserM

RestAPI -- WebApp
C1 -[hidden]- C2
@enduml
----
[options="header",cols="1,3"]
|===
|Component| Description
|Azure Server| Both the frontend and the backend will be hosted from docker containers, both of them inside an Azure virtual machine.
|WebApp | The frontend of the application, which will receive the user's requests and ask the RestAPI for its services.
|Rest API | Manages the requests from the web application and fetches the data from the corresponding place.
|Database|A documental database, which will store the minimal link information about the users.
|Map Provider|An external service to get the maps for the application.
|User|The user of the application.
|User Machine|The device from which the user will interact with the application.
|POD|Stores the user's data.
|===