[[section-concepts]]
== Cross-cutting Concepts
The application manages a lot of information. As such, it is required to define and explain some of them to reflect its internal workings.

=== Domain model
The following domain diagram and its description aims to describe the entities the application manages.

[plantuml,"Domain Model",svg]
----
@startuml
enum Visibility{
    PUBLIC
    PRIVATE
    FRIEND
}

enum Category {
    BAR
    MONUMENT
    MUSEUM
    RESTAURANT
    SIGHT
    SHOP
}

class User{
    username : string
    webId : string
    photo : string
}

class Review {
    place : string
    owner : string
    date : Date
    visibility : Visibility
}

class Place{
    name : String
    coordinates : Coordinates
}

class Picture{
    url : String
}

class Comment{
    text : String
}

class Score{
    score : int
}

Visibility -[hidden]d- Category

User -[hidden]l-- Place

User "1" -up- "0..n" Review
User "1" -- "0..n" User : is friends with
User "1" --- "n" Place

User -[hidden]right- Place
Picture -[hidden]right- Comment
Comment -[hidden]right- Score

Score --d|> Review
Picture --d|> Review
Comment --d|> Review

Review o-- Place
Place -l- Category
Visibility -d- Place
Review -l- Visibility

@enduml
----

[options="header", cols = "1, 4"]
|===
| Element | Description and purpose
| User | The people that use the application.
| Visibility | The privacy level of elements of the application (markers, reviews, scores, etc.) can be managed. Either public, private or friend-only levels are currently supported.
| Place | They represent the points on the map (they can be either created by users or be given by the application).
| Category | Places are classified into cateogries.
| Picture | Users can upload pictures to places.
| Score | Users can score places.
| Comment | Users can upload comments to places.
| Route | They are sets of places, of the same category.
| Role | Users can be classified into different roles.
|===

=== Security and user privacy

In order to increase security and privacy, all users authenticate through their POD, that will store their data, friends and maps. This way the users can decide who can see and use their information, giving them more freedom and control over the data they share.

=== Persistence

A document database will be used to store metadata about entities in the domain model. This metadata is intended to link entities with their containers, for example linking a comment to its associated place.

==== Structure of link data

The concept of link data aims to provide a faster, more private way of handling information inside the application. It works as follows: entities (such as places or reviews) are stored in each user's POD, and have a UUID associated with them. They only contain data about themselves, such as names, links or webIds.
They do not contain other entities (for example, in the case of places, they don't contain its reviews), but that information is stored in the database as small documents that contain the two entities to link, as well as some extra information to include the privacy level of the item and the webId of the owner.

Refer to link:05_building_block_view.adoc#_database[database schema] for a representation of this data.


=== Session management

Since the POD is the only identity 'token' the application uses, each person will only sign in and have access to their saved data through it. Passwords will only be used by the Identity Provider to ensure the correct user is giving access to the POD's resources.

As a consequence, the application does not have to manage users. At a more basic level, the application is just another POD browser: it manages data stored in the PODs of users.