[[section-concepts]]
== Cross-cutting Concepts
The application manages a lot of information. As such, it is required to define and explain some of them to reflect its internal workings.

=== Domain model
The following domain diagram and its description aim to describe the entities the application manages. It is important to note that some of these entities are, as of now, not implemented or lacking their functionality.

[plantuml,"Domain Model",svg]
----
@startuml
enum Visibility{
    PUBLIC
    PRIVATE
    FRIEND
}

class Place{
    name : String
    coordinates : Coordinates
}

class Category{
    name : String
}

class Picture{
    url : String
}

class Comment{
    text : String
}

class Score{
    score : int
}

class Route{
    name : String
}

class User{
    username : String
    webId : String
}

enum Role{
    CITIZEN
    TOURIST
    BUSINESS
}



Place "0..n" -down- "1" Category
Place o-down- "0..n" Picture
Place o-down- "0..n" Comment
Place o-down- "0..n" Score


User "1" -up- "0..n" Picture
User "1" -up- "0..n" Comment
User "1" -up- "0..n" Score
User "1" -- "0..n" User : is friends with
User "1" -left- "0..n" Place

Route "0..n" -- "1" Category
Route "0..n" -left- "0..n" Place

@enduml
----

[options="header", cols = "1, 4"]
|===
| Element | Description and purpose
| User | The people that use the application.
| Visibility | The privacy level of elements of the application (markers, reviews, scores, etc.) can be managed. Either public, private or friend-only levels are currently supported.
| Place | They represent the points on the map (they can be either created by users or be given by the application).
| Category | Places are classified into cateogries.
| Picture | Users can upload pictures to places.
| Score | Users can score places.
| Comment | Users can upload comments to places.
| Route | They are sets of places, of the same category.
| Role | Users can be classified into different roles.
|===


=== Security and user privacy

In order to increase security and privacy, all users authenticate through their POD, that will store their data, friends and maps. This way the users can decide who can see and use their information, giving them more freedom and control over the data they share.


=== Persistence

A document database will be used to store metadata about entities in the domain model. This metadata is intended to link entities with their containers, for example linking a comment to its associated place.


=== Session management

Since the POD is the only identity 'item' the application uses, each person will only sign in and have access to their saved data through it. Passwords will only be used by the Identity Provider to ensure the correct user is giving access to the POD's resources.
