[[section-quality-scenarios]]
== Quality Requirements

=== Quality Tree

The quality tree classifies the qualities the system will be evaluated about. We divide them in four main categories: Usability, Operational, Integrity and Maintainability & Support.

[plantuml, "Quality Tree", svg]
----
@startuml
node Quality as "Quality Categories"

card Usability
storage EoU as "Ease of Use"
storage EoL as "Ease of Learning"

card Operability
storage Availability
storage Performance
storage Robustness

card Integrity
storage Sec as "Security"
storage Priv as "Privacy"

card MaS as "Maintainability & Support"
storage Testability
storage Maintainability

Quality -d-> Operability
Quality -d-> Integrity
Quality -d-> Usability
Quality -d-> MaS

Usability -d-> EoU
Usability -d-> EoL

Operability -d-> Availability
Operability -d-> Performance
Operability -d-> Robustness

Integrity -d-> Sec
Integrity -d-> Priv

MaS -d-> Maintainability
MaS -d-> Testability
@enduml
----

=== Quality Scenarios

The quality scenarios propose metrics and methods used to evaluate the quality requirements of the application. This table is classified by quality category.

[options="header",cols="1,2,2,5,1,1"]
|===
|Code|Quality category|Quality attribute|Scenario|Priority|Implementation complexity

|QS1|Usability|Ease of Use|The application should be usable on a computer.|Medium|Medium

|QS2|Usability|Ease of Learning|A new user wants to find a place with the app in less than 5 minutes.|High|Low

|QS3|Operability|Availability|The application must be available the 99% of the time.|Medium|High

|QS4|Operability|Performance|25 concurrent users request the map of a given city in less than 10 seconds.|High|High

|QS5|Operability|Robustness|The application should keep working for other users if one user experiences problems.|Medium|Medium
|QS6|Integrity|Security|User data must be transmitted and stored securely.|Low|High

|QS7|Integrity|Privacy|Sensible user data will not be accessible for anyone but the user.|High|Medium
|QS8|Maintainability & Support|Testability|The application should have a test coverage greater than 80%. |High|Low

|QS9|Maintainability & Support|Maintainability|The code should be clear and documented enough to allow new developers to join the project.|Low|Low

|===
